### PR TITLE
#14: fix the path

### PR DESCRIPTION
**Pull request by dmazurek**

### CODE REVIEW

**Review by jermahs — COMMENTED** [review]
@dmazurek are you sure this works? I am fairly confident I tested this the other day and it was working. This is only dev not prod configs.

**Comment by dmazurek** [comment]
It didn't for me, but maybe my config is weird? When I go to http://localhost:8080, I see in the server window:

Request URL!:  /karaoke/api/karaoke/api/playlist

When I get rid of the extra stuff, it goes to:

Request URL!:  /karaoke/api/playlist

**Comment by jermahs** [comment]
@dmazurek yeah you're definitely right. I just tried it myself when testing another PR of yours and I ran into the same issue.

**Review by jermahs — APPROVED** [review]
definitely right

**Pull request merged**
